package main.model;

/**
 * User — ABSTRACT BASE CLASS
 *
 * WHAT IS AN ABSTRACT CLASS?
 * ==========================
 * An abstract class is a class that CANNOT be instantiated directly.
 * You can't do: User u = new User(...) ← This will give compile error!
 *
 * WHY make it abstract?
 * Because a "User" by itself doesn't make sense in our system.
 * Every user must be either a Student, Tutor, or Admin.
 * The abstract class holds the COMMON attributes/methods that all users share.
 *
 * INHERITANCE HIERARCHY (from your Class Diagram):
 *
 * User (abstract)
 * ↓
 * Student
 * ↓
 * Tutor (a Tutor IS a Student who also teaches)
 */
public abstract class User {

    // ─── Common Attributes (every user has these) ───
    protected int userId; // auto-generated by database
    protected String name;
    protected String email;
    protected String password; // will be hashed later
    protected String role; // "STUDENT", "TUTOR", or "ADMIN"

    // ─── Constructor ───
    // 'protected' because only subclasses (Student, Tutor) should call this
    protected User(int userId, String name, String email, String password, String role) {
        this.userId = userId;
        this.name = name;
        this.email = email;
        this.password = password;
        this.role = role;
    }

    // Constructor without userId (for NEW users before DB insert)
    protected User(String name, String email, String password, String role) {
        this(-1, name, email, password, role); // -1 means "not yet saved"
    }

    // ─── Abstract Method ───
    // Each subclass MUST implement this. Forces Student and Tutor
    // to display their info differently.
    public abstract String displayProfile();

    // ─── Getters ───
    public int getUserId() {
        return userId;
    }

    public String getName() {
        return name;
    }

    public String getEmail() {
        return email;
    }

    public String getPassword() {
        return password;
    }

    public String getRole() {
        return role;
    }

    // ─── Setters ───
    public void setUserId(int userId) {
        this.userId = userId;
    }

    public void setName(String name) {
        this.name = name;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    @Override
    public String toString() {
        return role + " [id=" + userId + ", name=" + name + ", email=" + email + "]";
    }
}
